// This file was autogenerated by C:\dev\Projects\Misc\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../../labs/jish/js.net.tests/resources/closure_command_test/main.js', ['jish.test.main'], ['jish.test.util']);
goog.addDependency('../../../../labs/jish/js.net.tests/resources/closure_command_test/util.js', ['jish.test.util'], ['goog.string']);
